### ISSUE TITLE
Black Hololens camera stream and un-pinchable menu button

### ISSUE THREAD

**Issue by gftrotta** [EnoxSoftware/HoloLensWithDlibFaceLandmarkDetectorExample#1]
Hi all,
I have some issue on ARHeadExample project as you can read in issue title.

All the requirements written in readme file are respected.
All the steps to build the project on HoloLens have been followed.

What could be the problem?

Thanks in advance

**Comment by EnoxSoftware** [comment]
Are other examples(HoloLensFaceLandmarkDetectionExample HoloLensPhotoCaptureExample HoloLensWebCamTextureExample) working without problems?

**Comment by gftrotta** [comment]
Nope. The camera led on the HoloLens does not turn on.

**Comment by gftrotta** [comment]
Maybe, even .xml for face detection must be in Assets/StreamingAssets??

**Comment by EnoxSoftware** [comment]
![hololenswithdlibexample_iss](https://user-images.githubusercontent.com/7920392/36207732-4530ab04-11da-11e8-9f5c-f38c17003f72.jpg)

**Comment by gftrotta** [comment]
Yep... but the readme file quotes:

Import the OpenCVForUnity.
Setup the OpenCVForUnity. (Tools > OpenCV for Unity > Set Plugn Inport Settings)
Import the DlibFaceLandmarkDetector.
Setup the OpenCVForUnity. (Tools > Dlib FaceLandmarkDetector > Set Plugn Inport Settings)
Move the "DlibFaceLandmarkDetector/StreamingAssets/sp_human_face_68.dat" and "DlibFaceLandmarkDetector/StreamingAssets/sp_human_face_68_for_mobile.dat" to the "Assets/StreamingAssets/" folder.

While for dlib is written that .dat file is to be moved (for the pose predictor), for opencv this is not written (for the face detector .xml files).

**Comment by EnoxSoftware** [comment]
Thank you very much for your attention.
I fixed README.md.
Move the "OpenCVForUnity/StreamingAssets/haarcascade_frontalface_alt.xml" and "OpenCVForUnity/StreamingAssets/lbpcascade_frontalface.xml" to the "Assets/StreamingAssets/" folder.
