### ISSUE TITLE
Does this work with Hololens2?

### ISSUE THREAD

**Issue by Abdul-Mukit** [EnoxSoftware/HoloLensWithDlibFaceLandmarkDetectorExample#3]

**Comment by x3a** [comment]
@Abdul-Mukit Did you had any further progress with this in the meantime?

I was able to get this example partially working by rebuilding the [HoloLensCameraStream](https://github.com/camnewnham/HoloLensCameraStream).dll with the help of [this issue](https://github.com/EnoxSoftware/HoloLensWithOpenCVForUnityExample/issues/29).

Now I have camera access and can even see the rectangular indicator over faces when I enable the camera preview, however, except for the menus and the camera preview pane no elements are rendered in the UI which seems odd.
